### ISSUE TITLE
按照文档subfix create --source_dir origin --output demo.list 自动生成音频数据集报错

### ISSUE THREAD

**Issue by TzyTman** [cronrpc/SubFix#12]
usage: subfix create [-h] {modelscope,whisper} ...
subfix create: error: argument solution: invalid choice: 'origin' (choose from 'modelscope', 'whisper')
 这框架根本没法玩啊！

**Comment by cronrpc** [comment]
由于modelscope的API进行了改动，导致之前的代码失效了，我更新了代码，同时需要更新下modelscope的版本。
具体操作见https://github.com/cronrpc/SubFix/issues/11
