### ISSUE TITLE
SubFix 能不能批量处理音频？ 

### ISSUE THREAD

**Issue by TzyTman** [cronrpc/SubFix#13]
是不是一次只能处理一个音频？

**Comment by cronrpc** [comment]
可以处理多组音频。将音频放置成如下格式，`origin/sam/a.wav`,`origin/sam/b.mp3`,'origin/sam/c.mp3'，然后可以统一处理。

**Comment by TzyTman** [comment]
意思是将多个音频放在origin/sam 路径下就行了 好的 多谢
