### ISSUE TITLE
在Windows 下 是不是不需要安装sudo apt install build-essential sudo apt install ffmpeg sudo apt install libsox-dev？

### ISSUE THREAD

**Issue by TzyTman** [cronrpc/SubFix#15]
在Windows 下 是不是不需要安装
sudo apt install build-essential
 sudo apt install ffmpeg 
sudo apt install libsox-dev

**Comment by TzyTman** [comment]
在Windows环境
如果有gpu，需要提前安装pytorch的cuda版本，配置ffmpeg等环境变量，之后执行下列命令

git clone https://github.com/cronrpc/SubFix.git
cd SubFix
pip install "modelscope[audio_asr]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
pip install -e .

**Comment by cronrpc** [comment]
windows下不需要安装那些。windows下需要配置ffmpeg环境变量。

**Comment by TzyTman** [comment]
已解决多谢楼主
