### ISSUE TITLE
如何设置modelscope默认加载模型不在c盘 而是指定当前项目某个文件夹下

### ISSUE THREAD

**Issue by qiuxin610** [cronrpc/SubFix#16]
目前想从默认的c盘下user的.cache下载的模型 挪到当前项目文件夹下。如何修改

**Comment by cronrpc** [comment]
参考代码：
https://github.com/modelscope/modelscope/blob/a903ec7a898f5dfb44349e2ce15971ec5f08e528/modelscope/hub/utils/utils.py#L42
设置一个环境变量，`MODELSCOPE_CACHE`。
