### ISSUE TITLE
pip install -e .打包后复制到其他电脑使用失败

### ISSUE THREAD

**Issue by qiuxin610** [cronrpc/SubFix#18]
请教一下 我在一台windows下 通过pip install -e .  打包好的subfix.exe  在单独的Python环境中，我把整个Python环境和工程copy到另一台电脑 就不行，是不是每台电脑需要自己打包一次，请问有办法解决么。

**Comment by cronrpc** [comment]
打包成一个exe不太了解，涉及的依赖比较多。一般可以做成整合包的形式，然后通过.bat启动。

**Comment by qiuxin610** [comment]
整合包方式也出现问题了，下载源码后  通过pip install -e.命令后 会在Python的目录Scripts目录中生成一个subfix.exe，这个subfix.exe 我复制到另一台电脑就直接报错ailed to create process.  当然我是把整个Python目录环境都复制到另一台电脑，想问下有办法解决么

**Comment by cronrpc** [comment]
没有处理过类似问题，不太清楚解决方法。
