### ISSUE TITLE
【需求】日语、英文的支持

### ISSUE THREAD

**Issue by Ikaros-521** [cronrpc/SubFix#2]
如题

**Comment by cronrpc** [comment]
@Ikaros-521 好的。目前在最新版中，已经调用`modelscope`的多语言标注部分。添加了speech_UniASR的日语、英语、韩语等ASR功能。

**Comment by Ikaros-521** [comment]
> @Ikaros-521 好的。目前在最新版中，已经调用`modelscope`的多语言标注部分。添加了speech_UniASR的日语、英语、韩语等ASR功能。

🤩大佬太强了
