### ISSUE TITLE
【需求】新增删除时将音频文件移动到另一个文件夹的功能

### ISSUE THREAD

**Issue by zxcvbnjftyruiepq** [cronrpc/SubFix#4]
用Bert-VITS2可以不移动音频文件，因为他是根据list来训练的。但是用来训练Retrieval-based-Voice-Conversion，他是训练整个文件夹的音频，这样就不方便了。做不到处理一次音频，可以同时用在两个地方。

希望采纳。

**Comment by cronrpc** [comment]
很好的建议。现在在最新版中，输入`subfix webui --force_delete True`启动webui时，每次**删除**和**合并**音频，都将同步对硬盘上的文件进行更改。
