### ISSUE TITLE
自己写好了移动未使用WAV的功能，打标了300句，应该没有BUG。。

### ISSUE THREAD

**Issue by zxcvbnjftyruiepq** [cronrpc/SubFix#5]
'''
移动list中没有使用的wav至del文件夹（del文件夹需要手动新建）
'''
import shutil

def b_del_file():
    # 遍历list同级别文件夹下的wav文件
    directory_path = os.path.dirname(g_load_file)

    for file in os.listdir(directory_path):
        if file.endswith(".wav"):
            is_exists = False

            # 遍历处理后的list
            for data in g_data_json:
                if os.path.basename(data['wav_path']) == file:
                    is_exists = True
                    break

            # 处理后的list没有当前文件，移动到del
            if not is_exists:
                source_file = os.path.join(directory_path, file)
                target_file = os.path.join(directory_path, 'del', file)
                shutil.move(source_file, target_file)

def b_save_file():
    if g_load_format == "json":
        b_save_json()
    elif g_load_format == "list":
        b_save_list()
        b_del_file()

**Comment by cronrpc** [comment]
谢谢。暂不考虑在主线添加这个功能。可以单独作为一个程序来执行。
