### ISSUE TITLE
请求在bert-vits2整合包中集成subfix

### ISSUE THREAD

**Issue by YYuX-1145** [cronrpc/SubFix#6]
您好！我希望能够在我制作的bert-vits2整合包中集成您的subfix工具（不含打标功能）。如果您同意的话，我的训练管理器会提供启动subfix的入口。并且由于不同版本gradio组件更新方法不同，我可能会对您的一些代码进行修改，也可能加入一些新的功能。目前整合包的全部代码开源。也会在readme中进行说明。顺带问一下，您使用的gradio版本是哪一个？

**Comment by cronrpc** [comment]
好的。README中演示的是3.50.2的版本。

**Comment by YYuX-1145** [comment]
感谢！

**Comment by AIpythonAI** [comment]
Hello @YYuX-1145 , can you open the repo BERT VITS 2 package? I would like to write an issue there please ^^
Thanks :). (Sorry I could not contact you elsewhere).
Good day
