### ISSUE TITLE
modelscope 安装失败

### ISSUE THREAD

**Issue by yanfaze** [cronrpc/SubFix#8]
执行 pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html 这个命令是总是提示
![image](https://github.com/cronrpc/SubFix/assets/12097100/7c8dae74-08d1-4061-852a-9e673aa16097)

我看说这个modelscope 只能在linux上运行吗

**Comment by cronrpc** [comment]
根据我最新的测试，windows下可以使用命令

pip install "modelscope[audio_asr]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

我同时更新了一下README中的Windows安装说明，可以参考一下。

还可以参考一下：https://blog.csdn.net/qq_42815746/article/details/130578340

目前我测试了在Windows下中文自动标注可以成功。
